<footer class="mainfooter">
           <a href="http://www.facebook.com" title="Facebook Link"><img class="foot_logo" src="assets/media/img/facebook-logo.png" alt="Facebook Logo" /></a>
          <p>Copyright &copy; <a href="#" title="Peter Clarke Designs">PeterClarkeDesigns.com</a></p>
          <a href="http://www.twitter.com" title="Twitter Link"><img class="foot_logo" src="assets/media/img/twitter-logo.png" alt="Twitter Logo" /></a>
          <br>
          <p><a href="terms_conditions.php" title="Terms and Conditions">Terms & Conditions</a></p>
          <p><a href="privacy_policy.php" title="Privacy Policy">Privacy Policy</a></p>
  </footer>