<link rel="stylesheet" href="assets/css/core.css" type="text/css" />
    <script src="assets/js/modernizr.min.js"></script>
  </head>
  
  
  <body>
  <div id="wrapper">
      <header class="mainheader">
          
          <img class="logo" src="assets/img/logo-by-itself.gif" alt="Brighton Comic Arts Festival Logo" />
          
              <div class="slideshow">
                <p>

                    <img src="assets/img/Comic_Signing.jpg" alt="Comic Signing Event"/>
                    <img src="assets/img/Comic_Signing2.jpg" alt="Comic Signing Event2" />
                    <img src="assets/img/Comic_Signing3.jpg" alt="Comic Signing Event3" />
                    <img src="assets/img/Convention_Interior.jpg" alt="Convention Centre" />
                </p>
            </div>
          
      <?php include('nav.inc');?>    
      </header>