<nav class="topnav">
              <ul>
                  <li><a href="index.php">Home</a></li>
                  <li><a href="about.php">About</a></li>
                  <li class="dropmenu"><a href="events.php">Events</a>
                      <ul>
                          <li><a href="events_day.php">By Day</a></li>
                          <li><a href="events_zone.php">By Zone</a></li>
                      </ul>
                  </li>
                  <li class="dropmenu"><a href="merchandise.php">Merchandise</a>
                       <ul>
                          <li><a href="merchandise_shirts.php">Shirts</a></li>
                          <li><a href="merchandise_mugs.php">Mugs</a>  </li>  
                      </ul>
                  </li>
                  <li id="lastnav"><a href="contact.php">Contact Us</a></li>
              </ul>
</nav>